import fs from 'fs';

const lines = fs.readFileSync('src/App.jsx', 'utf8').split('\n');

function extract(start, end, dest, imports, functionName) {
    let content = lines.slice(start - 1, end).join('\n');
    content = content.replace(new RegExp('function ' + functionName), 'export default function ' + functionName);
    fs.writeFileSync(dest, imports + '\n\n' + content);
}

extract(239, 484, 'src/components/graph/GraphCanvas.jsx', 'import { useState, useEffect, useRef, useContext } from "react";\nimport { useAnimationFrame } from "../../hooks/useAnimationFrame";\nimport { ThemeContext, SERIF } from "../../context/ThemeContext";\nimport { GRAPH_NODES, GRAPH_EDGES, NODE_COLORS, DEFAULT_COLOR, NODE_DESCRIPTIONS } from "../../data/constants";', 'GraphCanvas');
extract(570, 677, 'src/components/hero/HeroTraces.jsx', 'import { useRef, useEffect, useContext } from "react";\nimport { useAnimationFrame } from "../../hooks/useAnimationFrame";\nimport { ThemeContext } from "../../context/ThemeContext";', 'HeroTraces');
extract(682, 773, 'src/components/hero/MiniTerminal.jsx', 'import { useState, useEffect, useRef, useContext } from "react";\nimport { ThemeContext, MONO } from "../../context/ThemeContext";', 'MiniTerminal');
extract(778, 803, 'src/components/ui/CVButton.jsx', 'import { useState, useContext } from "react";\nimport { ThemeContext, MONO } from "../../context/ThemeContext";', 'CVButton');
extract(808, 853, 'src/components/hero/HeroPicture.jsx', 'import { useContext } from "react";\nimport { ThemeContext, MONO } from "../../context/ThemeContext";\nimport { useMediaQuery } from "../../hooks/useMediaQuery";\nimport heroPhoto from "../../assets/pict.webp";', 'HeroPicture');
extract(855, 994, 'src/components/backgrounds/InteractiveBackgroundGraphs.jsx', 'import { useRef, useEffect, useCallback, useContext } from "react";\nimport { ThemeContext } from "../../context/ThemeContext";\nimport { useMediaQuery } from "../../hooks/useMediaQuery";\nimport { useAnimationFrame } from "../../hooks/useAnimationFrame";', 'InteractiveBackgroundGraphs');
extract(1014, 1215, 'src/components/sections/ProjectsSection.jsx', 'import { useRef, useState, useEffect, useContext } from "react";\nimport { ThemeContext, MONO, SERIF } from "../../context/ThemeContext";\nimport { useMediaQuery } from "../../hooks/useMediaQuery";\nimport { PROJECTS } from "../../data/constants";\nimport InteractiveBackgroundGraphs from "../backgrounds/InteractiveBackgroundGraphs";\nimport SectionLabel from "../ui/SectionLabel";\nimport DotGrid from "../ui/DotGrid";\nimport GraphCanvas from "../graph/GraphCanvas";', 'ProjectsSection');
extract(1220, 1306, 'src/components/sections/ConceptField.jsx', 'import { useContext } from "react";\nimport { ThemeContext, MONO } from "../../context/ThemeContext";\nimport { useMediaQuery } from "../../hooks/useMediaQuery";\nimport { GRAPH_NODES, GRAPH_EDGES } from "../../data/constants";\nimport InteractiveBackgroundGraphs from "../backgrounds/InteractiveBackgroundGraphs";\nimport SectionLabel from "../ui/SectionLabel";\nimport SectionHeading from "../ui/SectionHeading";\nimport DotGrid from "../ui/DotGrid";\nimport GraphCanvas from "../graph/GraphCanvas";', 'ConceptField');
extract(1311, 1481, 'src/components/backgrounds/ConwaysGameOfLife.jsx', 'import { useRef, useEffect, useContext } from "react";\nimport { ThemeContext } from "../../context/ThemeContext";\nimport { useAnimationFrame } from "../../hooks/useAnimationFrame";', 'ConwaysGameOfLife');
extract(1486, 1614, 'src/components/sections/ExperienceSection.jsx', 'import { useState, useContext } from "react";\nimport { ThemeContext, MONO, SERIF } from "../../context/ThemeContext";\nimport { useMediaQuery } from "../../hooks/useMediaQuery";\nimport { EXPERIENCE } from "../../data/constants";\nimport SectionLabel from "../ui/SectionLabel";\nimport SectionHeading from "../ui/SectionHeading";', 'ExperienceSection');
extract(1993, 2084, 'src/components/sections/ExploringSection.jsx', 'import { useContext } from "react";\nimport { ThemeContext, MONO } from "../../context/ThemeContext";\nimport { useMediaQuery } from "../../hooks/useMediaQuery";\nimport { EXPLORING, STATUS_COLORS_DARK } from "../../data/constants";\nimport SectionLabel from "../ui/SectionLabel";\nimport SectionHeading from "../ui/SectionHeading";', 'ExploringSection');
extract(2089, 2212, 'src/components/sections/AboutSection.jsx', 'import { useContext } from "react";\nimport { ThemeContext, MONO, SERIF } from "../../context/ThemeContext";\nimport { useMediaQuery } from "../../hooks/useMediaQuery";\nimport SectionLabel from "../ui/SectionLabel";\nimport CVButton from "../ui/CVButton";\nimport InteractiveBackgroundGraphs from "../backgrounds/InteractiveBackgroundGraphs";', 'AboutSection');
